version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Vanity-Generator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5wwv2cwht4q7"
s3_prefix = "Vanity-Generator"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
